# Travel charges
ADULT_TRAVEL_CHARGE: int = int(200)
SENIOR_CITIZEN_TRAVEL_CHARGE: int = int(100)
KID_TRAVEL_CHARGE: int = int(50)


# Metro card service constants
RECHARGE_FEE_PERCENTAGE: float = 0.02
DISCOUNT_DIVISOR: int = 2
SORT_BY_VALUE_DESCENDING: int = -1
STATION_NAME_INDEX: int = 0
PASSENGER_COUNT_INDEX: int = 1
ZERO_DISCOUNT: int = 0


# Geektrust constants
ARGUMENTS_LENGTH: int = 2
FILE_PATH_ARGUMENT_INDEX: int = 1
EXIT_FILE_NOT_FOUND: int = 1
BALANCE_ARGS_LENGTH: int = 3
CHECK_IN_ARGS_LENGTH: int = 4
INPUT_COMMAND_FIRST_WORD_INDEX: int = 0
INPUT_COMMAND_CARD_ID_INDEX: int = 1
INPUT_COMMAND_BALANCE_INDEX: int = 2
INPUT_COMMAND_PASSENGER_TYPE_INDEX: int = 2
INPUT_COMMAND_STATION_NAME_INDEX: int = 3